version: '3'

services:
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/social_network
    ports:
      - '8000:8000'
    depends_on:
      - db

  db:
    image: postgres:14.0-alpine
    env_file: .env
    restart: always
    volumes:
      - db_postgres:/var/lib/postgresql/data


volumes:
  db_postgres:
  my-datavolume:
