# Generated by Django 4.2 on 2023-10-23 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='device',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='os',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='os_version',
        ),
    ]
